[package]
authors = ["Will Crichton <wcrichto@cs.stanford.edu>"]
edition = "2018"
name = "rust-slicer"
version = "0.1.0"

[dependencies]
anyhow = "1"
env_logger = "0.8"
log = "0.4"
fluid-let = "0.1"
take_mut = "0.2"

# For CLI
clap = "2.33"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
regex = "1"

[dev-dependencies]
tempfile = "3.2"
lazy_static = "1.4"

[profile.release]
debug = true
